// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwqdkfvqvknchtpcxwui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cWRrZnZxdmtuY2h0cGN4d3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzg5NDEsImV4cCI6MjA1OTQ1NDk0MX0.RpjbHBUbrJGjX6Qv8tXUyynMqf9CNKfkocdoYA8HUJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);