// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://winsgavulkyfhaxpnpoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbnNnYXZ1bGt5ZmhheHBucG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTcwNTIsImV4cCI6MjA2MDkzMzA1Mn0.-eJI8VWU9D618HnP7aZu3cn1I9j29RVQcWOfuKjC6qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);